parent=keycloak
import=common/keycloak

# Metadata
name=SSO Pemda DIY Theme
author=SSO Team
version=1.0.0

# Styles
styles=css/login.css

# Scripts (optional)
scripts=js/login.js

# Locales support
locales=id,en